local args = {...}
local length = tonumber(args[1])
 
if not length then
    print("Benutzung: " .. shell.getRunningProgram() .. " <Laenge>")
    return
end

	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.turnLeft()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()

for i = 1, length do
	
	
	
	turtle.turnRight()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.turnRight()
	
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	
	turtle.turnLeft()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.turnLeft()
	
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	
end

print("Fertig!")
