local args = {...}
local length = tonumber(args[1])
 
if not length then
    print("Benutzung: " .. shell.getRunningProgram() .. " <Laenge>")
    return
end

	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.turnLeft()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()

print("Länge erkannt: " .. length)
for i = 1, length do
    print("Durchlauf: " .. i .. " / " .. length)	
	
	
	turtle.turnRight()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.turnRight()
	
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	
	turtle.turnLeft()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.turnLeft()
	
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	turtle.dig()
	turtle.forward()
	turtle.digUp()
	turtle.digDown()
	
end

print("Fertig!")
